@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZSI6eyJfaWQiOiI2MjU0M2I0MzVhZjc4ZjAwNDRiNTdjODMiLCJuYW1lIjoiU291OWlubyIsInN1YmRvbWFpbiI6InNvdTlpbm8uc3RvcmVpbm8ud29ybGQifSwidXNlciI6eyJfaWQiOiI2MjU0M2I0MzVhZjc4ZjAwNDRiNTdjN2UiLCJmaXJzdG5hbWUiOiJhYmRlbGFsaSIsImxhc3RuYW1lIjoicmFmaWsiLCJlbWFpbCI6ImFiZGVsYWxpLnJhZmlrMTFAZ21haWwuY29tIn0sImNvbXBhbnkiOnsic3RhdHVzIjoiVU5DT01QTEVURUQiLCJfaWQiOiI2MjU0M2I0MzVhZjc4ZjAwNDRiNTdjN2MiLCJuYW1lIjoic291OWlubyJ9LCJ0b2tlbklkIjoiNDA0NDA1RklJQ05JNDU0MDY0WE9ZSFZYIiwiaWF0IjoxNjczOTQ4ODg3LCJleHAiOjE2NzQ4MTI4ODd9.XOVtwwRqOmVgbJNX4bBGf0rKREyjGlWsc_KoxwpOODc


###
GET https://admin.storeino.world/stores/api/themes/search?team._id=5f21374a175b5e8e309be827
X-Auth-Token: {{token}}

###
GET https://admin.storeino.world/stores/api/themes/update?team._id=5f21374a175b5e8e309be827
Content-Type: application/json
X-Auth-Token: {{token}}

{
  "team": {
    "name": "DEVELOPMENT",
    "url": "https://market.storeino.com/storeino/",
    "_id": "5f21374a175b5e8e309be827"
  }
}


