@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZTI4NDczOWRlOTM1MWJjNzNkMWZhYiIsImZpcnN0bmFtZSI6ImFiZGVsYWxpIiwibGFzdG5hbWUiOiJyYWZpazExIiwicG9zaXRpb24iOiJDTElFTlQiLCJlbWFpbCI6ImFiZGVsYWxpLnJhZmlrLjExQGdtYWlsLmNvbSIsImFkZHJlc3MiOm51bGx9LCJjb21wYW55Ijp7Il9pZCI6IjYwNDBhY2U4NGU4NzI0MDk1MGE3ZDhjOSIsIm5hbWUiOiJzdG9yZWlubyIsInN0YXR1cyI6IlVOQ09NUExFVEVEIn0sInN0b3JlIjp7Il9pZCI6IjYxOGYwMWVmNmZhZjNjMDE5ZTVkYTJlMSIsIm5hbWUiOiJsYW5kaW5nIiwic3ViZG9tYWluIjoibGFuZGluZy5zdG9yZWluby53b3JsZCJ9LCJ0b2tlbklkIjoiNjUzNjcxWVFaQlZQNjEzNTc3UUJTVEZLIiwiaWF0IjoxNjc1ODQ1MTc5LCJleHAiOjE2NzY3MDkxNzl9.lRdvQwbNBbAkYmsh1TpnWt2RDWV_AMnefbn8SlXAekM


###
GET https://admin.storeino.world/stores/api/themes/search?team._id=618f01ef6faf3c019e5da2e1
X-Auth-Token: {{token}}

###
GET https://admin.storeino.world/stores/api/themes/update?team._id=618f01ef6faf3c019e5da2e1
Content-Type: application/json
X-Auth-Token: {{token}}

{
  "team": {
    "name": "DEVELOPMENT",
    "url": "https://market.storeino.com/storeino/",
    "_id": "5f21374a175b5e8e309be827"

  }
}


